### ISSUE TITLE
REPL: doesn't load properly

### ISSUE THREAD

**Issue by mcuadros** [google/starlark-go#224]
Unless I am doing something wrong, `load` inside of a REPL, doesn't load the object to the global scope. 

```bash
> cat foo.star
foo = 42

> starlark
Welcome to Starlark (go.starlark.net)
>>> load("foo.star", "foo")
>>> foo
<stdin>:1:1: undefined: foo
>>>
```

**Comment by alandonovan** [comment]
Yikes, thanks for pointing this out. This appears to be a regression caused by 754257e: load bindings are now local to the "file". Each chunk (e.g. line) of REPL input is a file, so the REPL will need to work harder to dig the load bindings out of one "file" and transfer them to the next one.

**Comment by adonovan** [comment]
Fixed by the previous PR.
